# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 14:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizattempts',
            name='attempt_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
