# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_studentquizattempts_attempt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizattempts',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
